'%dev':
    quarkus:
        datasource:
            db-kind: postgresql
            password: ''
            reactive:
                url: postgresql://localhost:5432/groeiplein
            username: simon
        hibernate-orm:
            database:
                generation: update
            jdbc:
                timezone: Europe/Amsterdam
        http:
            cors:
                origins: /.*/
            port: 8082
            ssl: 
                certificate:
                    key-store-file: appspeyk.pfx 
                    key-store-password: 1234
'%prod':
    quarkus:
        datasource:
            db-kind: postgresql
            password: 0J32342ZPC11AC11!
            reactive:
                postgresql:
                    ssl-mode: require
                reconnect-attempts: 3
                url: postgresql://groeiplein-database.postgres.database.azure.com/groeiplein
            username: cuygbottcp
        hibernate-orm:
            database:
                generation: update
            jdbc:
                timezone: Europe/Amsterdam
        http:
            insecure-requests: enabled 
            ssl:
                certificate:
                    key-store-file: appspeyk.pfx 
                    key-store-password: 1234 
            cors:
              origins: /https://([a-z0-9\-_]+)\.sharepoint\.com/
mp:
    jwt:
        verify:
            issuer: https://sts.windows.net/27f15159-a16a-4f84-af73-f3fa4f121752/
            publickey:
                location: certificate.pem
    openapi:
        scan:
            disable: false
quarkus:
    hibernate-orm:
        log:
            sql: true
        second-level-caching-enabled: true
        statistics: true
    package:
        type: uber-jar
    smallrye-openapi:
        path: /openapi
    swagger-ui:
        always-include: true
        path: /swagger
    jib:
      base-jvm-image: registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
    rate-limiter:
        buckets:
            restapi:
                limits:
                    - permitted-uses: 100
                      period: 1S
                    - permitted-uses: 600
                      period: 1M
                identity-resolver: nl.speyk.resolver.UserResolver
