mp:
    jwt:
        verify:
            issuer: https://sts.windows.net/27f15159-a16a-4f84-af73-f3fa4f121752/ 
            publickey:
                location: https://login.microsoftonline.com/common/discovery/v2.0/keys
                algorithm: RS256
    openapi:
        scan:
            disable: false
quarkus:
    cache:
      enabled: true
    native:
      resources:
        includes: appspeyk.pfx,import.sql
    hibernate-orm:
        log:
            sql: true
        second-level-caching-enabled: false 
        statistics: true
    package:
        type: uber-jar
    smallrye-openapi:
        path: /openapi
    swagger-ui:
        always-include: true:w
        path: /swagger
    jib:
      base-jvm-image: registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
    rate-limiter:
        buckets:
            restapi:
                limits:
                    - permitted-uses: 100
                      period: 1S
                    - permitted-uses: 600
                      period: 1M
                identity-resolver: nl.speyk.utils.UserResolver
