speyk:
  jwt: jsonwebtoken
quarkus:
  datasource:
    db-kind: postgresql
    password: ''
    reactive:
      url: postgresql://localhost:5432/groeiplein_test
    username: simon
  hibernate-orm:
      database:
        generation: drop-and-create
      jdbc:
        timezone: Europe/Amsterdam
  http:
      cors:
        origins: /.*/
