quarkus:
  datasource:
      db-kind: postgresql
      password: ''
      reactive:
          url: postgresql://localhost:5432/groeiplein_dev
      username: simon
  hibernate-orm:
      database:
          generation: update
      jdbc:
          timezone: Europe/Amsterdam
  http:
      cors:
          origins: /.*/
      port: 8082
      ssl:
          certificate:
              key-store-file: appspeyk.pfx
              key-store-password: 1234
