'%test':
  speyk:
    jwt: jsonwebtoken
  quarkus:
    datasource:
      db-kind: postgresql
      password: ''
      reactive:
        url: postgresql://localhost:5432/groeiplein_test
      username: simon
    hibernate-orm:
        database:
          generation: drop-and-create
        jdbc:
          timezone: Europe/Amsterdam
    http:
        cors:
          origins: /.*/
'%dev':
    quarkus:
        datasource:
            db-kind: postgresql
            password: ''
            reactive:
                url: postgresql://localhost:5432/groeiplein_dev
            username: simon
        hibernate-orm:
            database:
                generation: update
            jdbc:
                timezone: Europe/Amsterdam
        http:
            cors:
                origins: /.*/
            port: 8082
            ssl:
                certificate:
                    key-store-file: appspeyk.pfx
                    key-store-password: 1234
'%prod':
    quarkus:
        datasource:
            db-kind: postgresql
            password: 0J32342ZPC11AC11!
            reactive:
                postgresql:
                    ssl-mode: require
                reconnect-attempts: 3
                url: postgresql://groeiplein-database.postgres.database.azure.com/groeiplein_dev
            username: cuygbottcp
        hibernate-orm:
            database:
                generation: update
            jdbc:
                timezone: Europe/Amsterdam
        http:
            insecure-requests: enabled
            ssl:
                certificate:
                    key-store-file: appspeyk.pfx
                    key-store-password: 1234
            cors:
               origins: /https://([a-z0-9\-_]+)\.sharepoint\.com/
mp:
    jwt:
        verify:
            issuer: https://sts.windows.net/d71896c5-795f-424e-bfb5-558dd1f95bb1/
            publickey:
                location: https://login.microsoftonline.com/common/discovery/v2.0/keys
    openapi:
        scan:
            disable: false
quarkus:
    native:
      resources:
        includes: appspeyk.pfx,certificate.pem,import.sql
    hibernate-orm:
        log:
            sql: true
        second-level-caching-enabled: false
        statistics: true
    package:
        type: uber-jar
    smallrye-openapi:
        path: /openapi
    swagger-ui:
        always-include: true
        path: /swagger
    jib:
      base-jvm-image: registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
    rate-limiter:
        buckets:
            restapi:
                limits:
                    - permitted-uses: 100
                      period: 1S
                    - permitted-uses: 600
                      period: 1M
                identity-resolver: nl.speyk.resolver.UserResolver
