package nl.speyk.coupledbestand;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.oauth2;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;


//All remaining API endpoints are automatically generated by Quarkus REST Panache, we only test for JSON Web Tokens.
@QuarkusTest
public class CoupledBestandJaxRsTest {

    @ConfigProperty(name = "speyk.jwt")
    String jwt;

    @Test
    public void getAllNoJwt() {
        given()
                .when()
                .get("/coupled-bestand")
                .then()
                .statusCode(401);
    }

    @Test
    public void getAllJWt() {
        given().auth().preemptive().oauth2(jwt)
                .when()
                .get("/coupled-bestand")
                .then()
                .statusCode(200);
    }
}
