package nl.speyk.coupledbestand;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.time.Duration;
import java.util.List;

import org.junit.jupiter.api.Test;

import io.quarkus.test.junit.QuarkusTest;
import io.smallrye.mutiny.Uni;
import jakarta.inject.Inject;

//All remaining entity methods are generated by Quarkus panache, we only test for additional methods.
@QuarkusTest
public class CoupledBestandResourceTest {

    @Inject
    CoupledBestandResource coupledBestandResource;

    @Test
    public void testFindMomentByLeerlingId() throws Exception {
        // Given
        Long inlevermomentId = 1L;
        // When
        Uni<List<CoupledBestand>> response = coupledBestandResource.findMomentByLeerlingId(inlevermomentId);
        // Then
        assertNotNull(response);
        List<CoupledBestand> result = response.await().atMost(Duration.ofSeconds(5));
        assertFalse(result.isEmpty());
        for (CoupledBestand coupledBestand : result) {
            // Verify the properties of each CoupledBestand in the result list
            assertNotNull(coupledBestand.filename);
            assertNotNull(coupledBestand.fileurl);
            assertNotNull(coupledBestand.inlevermoment);
        }
    }
}
