package nl.speyk.coupledbestand;

import java.time.Duration;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import io.quarkus.test.hibernate.reactive.panache.TransactionalUniAsserter;
import io.quarkus.test.junit.QuarkusTest;
import io.quarkus.test.vertx.RunOnVertxContext;
import jakarta.inject.Inject;

//All remaining entity methods are generated by Quarkus panache, we only test for additional methods
@QuarkusTest
@RunOnVertxContext
public class CoupledBestandResourceTest {

    // Given
    private static long inleverMomntId = 1;

    @Inject
    CoupledBestandResource coupledBestandResource;

    @Test
    public void testFindBestandenByInlevermomentId(TransactionalUniAsserter asserter) throws Exception {
        asserter.assertThat(() -> //when
                            coupledBestandResource.findBestandenByInlevermomentId(inleverMomntId),
                            bestanden -> {
                                 //then
                            Assertions.assertNotNull(bestanden);
                            for (CoupledBestand bestand : bestanden) {
                                Assertions.assertNotNull(bestand.id);
                            }
                            }
                            );
    }
}
